backend_params:
  base_set: default0
  nonretranspile_changes:
    geyser_dump_transpiled_qasm: [False]

benchmarks:
- name: algorithm
  type: ['hhl']
  n_qubits: [7]
- name: supermarq
  type: ['mermin_bell']
  n_qubits: [10]
- name: QASMBench
  type: ['QV']
  n_qubits: [32]
- name: QASMBench
  type: ['bv']
  n_qubits: [50]
- name: algorithm
  type: ['bv']
  n_qubits: [70]

- name: qsim_rand
  p: [0.5]
  keep_length: [10]
  n_qubits: [20]
  i: 1
- name: qsim_rand
  p: [0.5]
  keep_length: [10]
  n_qubits: [40]
  i: 1

- name: qsim_molecule
  type: ['H2', 'LiH']

- name: qaoa_rand
  p: [0.5]
  n_qubits: [10]
  i: 1
- name: qaoa_rand
  p: [0.5]
  n_qubits: [20]
  i: 1
- name: qaoa_regular
  regular: [5]
  n_qubits: [40]
  i: 1
- name: qaoa_regular
  regular: [6]
  n_qubits: [100]
  i: 1


- name: supermarq
  type: ['mermin_bell']
  n_qubits: [5]
- name: supermarq
  type: ['vqe_proxy']
  n_qubits: [10]
- name: supermarq
  type: ['vqe_proxy']
  n_qubits: [20]
- name: algorithm
  type: ['adder']
  n_qubits: [10]
- name: algorithm
  type: ['bv']
  n_qubits: [14]

- name: qsim_rand
  p: [0.5]
  keep_length: [10]
  n_qubits: [5]
  i: 1
- name: qsim_rand
  p: [0.5]
  keep_length: [10]
  n_qubits: [10]
  i: 1

- name: qaoa_rand
  p: [0.5]
  n_qubits: [5]
  i: 1
- name: qaoa_regular
  regular: [3]
  n_qubits: [20]
  i: 1
- name: qaoa_regular
  regular: [4]
  n_qubits: [10]
  i: 1
