count_gates: True
# All the backend parameters are given in the backend_params section in a list format. The experiments will be conducted for all the Cartesian products of the parameters.
backend_params:
  binding_params: ['n_rows', 'n_cols'] # In this case, these two parameters will be bound together, and not be used in the Cartesian product. For example, we will only have two experiments for this case instead of 4.
  retranspile_changes:
    n_rows: [[7,7,7],[8,8,8]] # The first element specify the number of rows for the SLM array and others specify the number of rows for each AOD arrays.
    n_cols: [[7,7,7],[8,8,8]] # The first element specify the number of columns for the SLM array and others specify the number of columns for each AOD arrays.
    n_aods: [2] # The number of AOD arrays. Should match the number of elements in n_rows and n_cols.
    atom_distance: ["15 * 1e-6"] # The distance between the atoms in the array.
    sc_simultaneous_1q_gate: ["1e10"] # The number of maximum simultaneous 1q gates for the superconducting qubits. Set to a large number means all 1q gates in the front layer can be executed simultaneously.
    sc_seed_transpiler: [0] # The seed for the qiskit transpiler.
    fpqac_generic_seed_transpiler: [0] # The seed for the qiskit transpiler.
    fpqac_qubit_array_mapper: ["default"] # Currently only default is supported.
    fpqac_qubit_atom_mapper: ["default"] # Support "default", "random" and "sequantial"
    fpqac_router: ["default"] # Support "default" and "serial"
    geyser_generic_seed_transpiler: [5] # The seed for the qiskit transpiler for FAA Triangular.
    faa_seed_transpiler: [0] # The seed for the qiskit transpiler for FAA Rectangular.
    full_report_path: ["None"] # The path to save the full report
    dump_full_report: [False] # Whether to dump the full report
    log_path: ["None"] # The path to save the log, if None, the log will be saved to corresponding folder as the config file.
    fpqac_generic_partition_method: ["heuristic"] # Support "heuristic" and "sabre", "SDP" and "dense"
    fpqac_generic_partition_factor: [0.9] # Set the decay factor for the partition method.
    fpqac_individual_addressable: [False]  # set to True to release constraint 1
    fpqac_allow_order_violation: [False]  # set to True to release constraint 2
    fpqac_allow_overlap_violation: [False]  # set to True to release constraint 3
  nonretranspile_changes: # These parameters will not be used during the transpilation process or the generated program, they are used to calculate some metrics like fidelity. So we won't retranspile the program for these parameters.
    T_per_move: ["300 * 1e-6"] # FPQC Hardware parameters
    x_zpf: ["38 * 1e-9"]
    omega_0: ["2 * np.pi * 80 * 1e3"]
    na_T1: ["1.5 * 10"]
    na_N_max: [33]
    na_1Q_time: ["1 / 3.2e6 * 4 / 2"]
    na_2Q_time: ["190 * 1e-9 * 2"]
    cooling_deltaN_thres: [15] # How many delta N is allowed before the cooling process.
    na_1Q_fidelity: [0.99992]
    na_2Q_fidelity: [0.9975]
    na_simultaneous_1q_gate: ["1e10"] # The number of maximum simultaneous 1q gates for the neutral atoms. Set to a large number means all 1q gates in the front layer can be executed simultaneously.
    lambd: [0.109375]
    atom_loss_prob: [0.0068]
    atom_transfer_time: [15 * 1e-6]
    sc_T1: ["None"] # Superconducting qubit parameters
    sc_T2: ["80.12 * 1e-6 * 10"]
    sc_1Q_time: ["160 * 0.22 * 1e-9"]
    sc_2Q_time: ["480 * 1e-9"]
