backend_params:
  base_set: default0
  nonretranspile_changes:
    geyser_dump_transpiled_qasm: [False]
    log_path: ["results/dump_full_report/log.pkl"]

benchmarks:
- name: algorithm
  type: ['hhl']
  n_qubits: [7]