backend_params:
  nonretranspile_changes:
    T_per_move: 
    - "100 * 1e-6"
    - "150 * 1e-6"
    - "200 * 1e-6"
    - "250 * 1e-6"
    - "300 * 1e-6"
    - "350 * 1e-6"
    - "400 * 1e-6"
    - "450 * 1e-6"
    - "500 * 1e-6"
    - "550 * 1e-6"
    - "600 * 1e-6"
    - "650 * 1e-6"
    - "700 * 1e-6"
    - "750 * 1e-6"
    - "800 * 1e-6"
    - "850 * 1e-6"
    - "900 * 1e-6"
    - "950 * 1e-6"
    - "1000 * 1e-6"
    - "1050 * 1e-6"
