backend_params:
  binding_params: ['n_rows', 'n_cols']
  retranspile_changes:
    # dump_full_report: [True]
    n_rows: 
    - [49,49,49]
    - [24,24,24]
    - [16,16,16]
    - [12,12,12]
    - [9,9,9]
    - [8,8,8]
    - [7,7,7]
    - [6,6,6]
    - [5,5,5]
    - [4,4,4]
    - [3,3,3]
    - [2,2,2]
    - [1,1,1]
    n_cols:
    - [1,1,1]
    - [2,2,2]
    - [3,3,3]
    - [4,4,4]
    - [5,5,5]
    - [6,6,6]
    - [7,7,7]
    - [8,8,8]
    - [9,9,9]
    - [12,12,12]
    - [16,16,16]
    - [24,24,24]
    - [49,49,49]