backend_params:
  nonretranspile_changes:
    na_T1: 
    - 0.05
    - 0.1
    - 0.2
    - 0.5
    - 0.8
    - 1
    - 2
    - 5
    - 8
    - 10
    - 20
    - 50
    - 80
    - 100
    - 200
    - 500
    - 800
    