backend_params:
  base_set: default0
  nonretranspile_changes:
    n_aods: [1]
    fpqac_qubit_atom_mapper: ['default']
    fpqac_router: ['default']
    fpqac_generic_partition_method: ["dense"]
    geyser_dump_transpiled_qasm: [False]
    n_rows: [12]
    n_cols: [12]

compiler:
  name: simple_heuristic