backend_params:
  base_set: default0
  nonretranspile_changes:
    geyser_dump_transpiled_qasm: [False]

benchmarks:
- name: supermarq
  type: ['mermin_bell']
  n_qubits: [5]
- name: supermarq
  type: ['vqe_proxy']
  n_qubits: [10]
- name: supermarq
  type: ['vqe_proxy']
  n_qubits: [20]
- name: algorithm
  type: ['adder']
  n_qubits: [10]
- name: algorithm
  type: ['bv']
  n_qubits: [14]
