compiler:
  print_log: False

backend_params:
  base_set: default0
  retranspile_changes: {}
    # na_1Q_time: [0.1]
    # na_1Q_fidelity: [0.99, 0.995]
  nonretranspile_changes: {}
    # sc_1Q_time: [0.1, 0.3]
    # sc_1Q_fidelity: [0.99, 0.995, 0.001, 0.003]
    # sc_2Q_time: [0.1, 0.3]
  # if empty:
  # nonretranspile_changes: {} 

# benchmarks:
  # - name: arbitrary
  #   n_qubits: [5, 10]
  #   n_gates: [10]
  #   i: 3
